name: C CI - The Compiler

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: sh install_dependencies.sh
    - name: make
      run: make
    - name: test1
      run: |
        ./etapa3 tests/stage3/input.txt output.txt
        echo ">> OUTPUT <<"
        cat output.txt
