name: C CI - The Compiler

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: sh install_dependencies.sh
    - name: make
      run: make
    - name: test1
      run: ./etapa1 tests/test1.txt
    - name: test2
      run: ./etapa1 tests/test2.txt
    - name: test3
      run: ./etapa1 tests/test3.txt
