name: C CI - The Compiler

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: sh install_dependencies.sh
    - name: make
      run: make
    - name: test1
      run: |

        ./etapa4 tests/stage4/in1.txt out.txt



        echo ">> OUTPUT <<"
        cat out.txt
